Repository wizzie-io/enricher, pull requests merged in 2018-11, with the labels that each got.

#14 WIZZIE-2299 Add global table support
  docs/_data/navigation.yml
  docs/assets/images/eql_syntax.png
  docs/configuration/eql_syntax.md
  model/src/test/java/io/wizzie/enricher/model/PlanModelUnitTest.java
  model/src/test/resources/plan-builder.json
  query-compiler/src/main/antlr4/io/wizzie/enricher/query/compiler/EnricherQL.g4
  query-compiler/src/main/java/io/wizzie/enricher/query/antlr4/Stream.java
  query-compiler/src/main/java/io/wizzie/enricher/query/internal/EnricherQLBaseVisitorImpl.java
  query-compiler/src/test/java/io/wizzie/enricher/query/EnricherCompilerUnitTest.java
  query-compiler/src/test/java/io/wizzie/enricher/query/EnricherQLUnitTest.java
  service/src/main/java/io/wizzie/enricher/builder/ChangeKeyHelper.java
  service/src/main/java/io/wizzie/enricher/builder/KSTable.java
  service/src/main/java/io/wizzie/enricher/builder/StreamBuilder.java
  service/src/test/java/io/wizzie/enricher/integration/QueryGlobalTableIntegrationTest.java
  service/src/test/java/io/wizzie/enricher/integration/QueryGlobalTablePartitionByIntegrationTest.java
  service/src/test/resources/query-with-global-table-integration-test.json
  service/src/test/resources/query-with-global-table-partition-by-integration-test.json
Labels: feature

#17 Fix null pointer exception at ChangeKeyHelper when message is null
  service/src/main/java/io/wizzie/enricher/builder/ChangeKeyHelper.java
Labels: bug

#18 Refactor EnricherQL to be more robust and update tests
  .gitignore
  query-compiler/pom.xml
  query-compiler/src/main/antlr4/io/wizzie/enricher/query/compiler/EnricherQL.g4
  query-compiler/src/main/antlr4/io/wizzie/enricher/query/compiler/EnricherQLLexer.g4
  query-compiler/src/main/antlr4/io/wizzie/enricher/query/compiler/EnricherQLParser.g4
  query-compiler/src/main/java/io/wizzie/enricher/query/EnricherCompiler.java
  query-compiler/src/main/java/io/wizzie/enricher/query/internal/EnricherQLBaseVisitorImpl.java
  query-compiler/src/test/java/io/wizzie/enricher/query/EnricherQLUnitTest.java
Labels: improvement

#20 WIZZIE-2948 Fix typos and misspelling errors in Enricher docs
  docs/configuration/base_configuration.md
  docs/configuration/bootstrapper.md
  docs/configuration/eql_syntax.md
  docs/configuration/metrics.md
  docs/configuration/multi_tenant.md
  docs/getting_started/base_tutorial.md
  docs/index.md
  docs/joiners_enrichers/enrichers.md
Labels: documentation

#23 Add env variables to allow file bootstrapper
  docker/build/Dockerfile
  docker/build/config_env.json
Labels: improvement

#21 WIZZIE-2948 Fix typos and misspelling errors in Enricher docs
  docs/configuration/base_configuration.md
  docs/configuration/bootstrapper.md
  docs/configuration/eql_syntax.md
  docs/configuration/metrics.md
  docs/configuration/multi_tenant.md
  docs/docker/docker_configuration.md
  docs/getting_started/base_tutorial.md
  docs/index.md
  docs/joiners_enrichers/enrichers.md
  docs/joiners_enrichers/joiners.md
Labels: documentation

#24 WIZZIE-3003 Add StaticDataEnrich enricher
  docs/joiners_enrichers/enrichers.md
  service/src/main/java/io/wizzie/enricher/enrichment/simple/impl/StaticDataEnrich.java
  service/src/test/java/io/wizzie/enricher/enrichment/simple/impl/StaticDataEnrichUnitTest.java
  service/src/test/java/io/wizzie/enricher/integration/StaticDataEnrichIntegrationTest.java
  service/src/test/resources/static-data-enrich-integration-test.json
Labels: improvement
