Repository wizzie-io/enricher, pull requests merged in 2018-12, with the labels that each got.

#28 Optimized imports
  extensions/src/test/java/io/wizzie/enricher/integration/GeoIpEnrichIntegrationTest.java
  service/src/main/java/io/wizzie/enricher/builder/StreamBuilder.java
  service/src/test/java/io/wizzie/enricher/integration/NullKeyJoinIntegrationTest.java
  service/src/test/java/io/wizzie/enricher/integration/QueryGlobalTableIntegrationTest.java
Labels: improvement

#29 Stream monitor
  docker/build/log4j2_env.xml
  extensions/src/test/resources/log4j2.xml
  service/src/main/java/io/wizzie/enricher/builder/Builder.java
  service/src/main/java/io/wizzie/enricher/builder/StreamMonitor.java
  service/src/main/resources/log4j2.xml
  service/src/test/resources/log4j2.xml
Labels: bug

#30 Logo printer
  service/src/main/java/io/wizzie/enricher/Enricher.java
  service/src/main/java/io/wizzie/enricher/logo/LogoPrinter.java
Labels: improvement

#31 Scalability docs
  docs/_data/navigation.yml
  docs/configuration/scalability.md
Labels: documentation

#32 Fix release deploy
  .circleci/config.yml
Labels: test

#33 Fix circle deploy
  .circleci/config.yml
Labels: test

#34 Fix docs
  docs/configuration/stream_configuration.md
Labels: documentation
